package icons

// Icon is a shared nerdfonts glyph placeholder.
// Populate these values with nerdfonts icons as needed.
const (
	Inbox     = ""
	Archive   = ""
	Trash     = ""
	Junk      = ""
	Drafts    = ""
	Sent      = ""
	AllMail   = ""
	Outbox    = ""
	Important = ""
	Star      = ""
	Unstar    = ""
	Flag      = ""
	Unflag    = ""

	ArrowUp              = ""
	ArrowDown            = ""
	ArrowUpDown          = ""
	ArrowLeft            = ""
	ArrowRight           = ""
	ArrowLeftRight       = ""
	ArrowUpRightDownLeft = ""
	ChevronUp            = ""
	ChevronDown          = ""
	ChevronLeft          = ""
	ChevronRight         = ""

	Refresh    = ""
	Search     = ""
	Filter     = ""
	Sort       = ""
	SortAsc    = ""
	SortDesc   = ""
	Expand     = ""
	Collapse   = ""
	Compose    = ""
	Edit       = ""
	Reply      = ""
	ReplyAll   = ""
	Forward    = ""
	Send       = ""
	Download   = ""
	Upload     = ""
	Attachment = "󰁦"
	Link       = ""
	Unlink     = ""

	Folder      = ""
	FolderOpen  = ""
	FolderEmpty = ""
	FolderNew   = ""
	FolderTree  = ""
	Tag         = ""
	Tags        = ""
	Label       = "󰌕"
	Pin         = "󰐃"
	Bookmark    = ""
	Unbookmark  = ""

	Unread     = ""
	Read       = ""
	MailOpen   = ""
	MailClosed = ""
	Syncing    = "󰓦"
	Synced     = ""
	Error      = ""
	Warning    = ""
	Success    = ""
	Info       = ""
	Lock       = ""
	Unlock     = ""
	Unlocked   = ""
	Shield     = ""
	Question   = ""

	Spinner1 = ""
	Spinner2 = ""
	Spinner3 = ""
	Spinner4 = ""
	Spinner5 = ""
	Spinner6 = ""

	Hourglass1 = ""
	Hourglass2 = ""
	Hourglass3 = ""

	ToggleOff = ""
	ToggleOn  = ""

	Settings   = ""
	Help       = ""
	Quit       = ""
	User       = ""
	Users      = ""
	Calendar   = ""
	Clock      = ""
	History    = ""
	Bell       = ""
	BellOff    = ""
	Plus       = ""
	Minus      = ""
	Equals     = ""
	Check      = ""
	Close      = ""
	Play       = ""
	Pause      = ""
	Stop       = ""
	Code       = ""
	Broom      = ""
	Database   = ""
	Delete     = ""
	FloppyDisk = ""
	Ghost      = ""
	Image      = ""

	Heart        = ""
	Heartbeat    = ""
	HeartEmpty   = ""
	HeartCracked = ""

	Package = "󰏓"
	Sparkle = ""
)
